title: Athena Rose Manjooran
description: Applied Physics & Clean Energy Research portfolio featuring research preprints, mathematical modeling, and educational resources.
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
google_site_verification: HOq5PX7DERPvndTNZuTbibr0lK6uJN7dYbH1Jl5-YTU
